### ISSUE TITLE
SimplePaginate with "page" attribute stop working.

### ISSUE THREAD

**Issue by Utwo** [jedrzej/searchable#22]
I installed pimpable package, but I think the problem is with searchable package.
When I have something like this:
`
Model::pimp()->simplePaginate();
`
It gives me:
`
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'page' in 'where clause' (SQL: select * from `sections` page = 1 limit 16 offset 0)
`
I found a way to allow everything except 'page' attribute, but it would be nice to have this effect in package.

My implementation in Model;
`
protected function getSearchableAttributes()
    {
        return array_except(Input::all(), 'page');
    }
    // or something like this
    public $searchableExcept = ['page'];
`

**Comment by jedrzej** [comment]
Hi @Utwo 
thanks for the tip, this issue has been fixed in 0.0.11. You should be able to define $notSearchable/getNotSearchableFields() blacklist to prevent selected fields from being filtered on.

You'll still need to explicitly add page there, as blacklisting it by default would be a breaking change.
